"""
AI Form Generator Agent

Generates proposal submission forms for RFPs created via AI Consultant chat.
This is an OPTIONAL feature - AI asks user if they want a form generated.
"""

from typing import Optional, List, Dict
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate

# Use unified AI client with fallback support
from backend.src.utils.ai_client import get_chat_llm

from backend.src.agents.form_structure_analyzer import (
    ProposalFormStructure,
    DiscoveredTable,
    DiscoveredColumn,
    DiscoveredFormRow
)


# --- Generation Models ---

class GeneratedLineItem(BaseModel):
    """A line item generated by AI based on RFP scope."""
    section: str = Field(description="Section name (e.g., 'General Work', 'Electrical', 'Labor')")
    item_id: str = Field(description="Item identifier (1, 2, 3...)")
    description: str = Field(description="Description of the work item")
    quantity: Optional[str] = Field(default="TBD", description="Estimated quantity if possible")
    unit: str = Field(description="Unit of measure (SF, LF, LS, HR, EA, etc.)")


class GeneratedProposalForm(BaseModel):
    """A proposal form generated by AI based on RFP data."""
    form_title: str = Field(description="Title for the proposal form")
    sections: List[str] = Field(description="List of section names")
    line_items: List[GeneratedLineItem] = Field(description="Generated line items")
    include_general_conditions: bool = Field(default=True, description="Include General Conditions table")
    include_additions: bool = Field(default=True, description="Include Additions table")


class AIFormGenerator:
    """
    Generates proposal submission forms based on RFP data collected via chat.
    
    Used in the AI Consultant flow when user opts to create a proposal form.
    """
    
    def __init__(self, model: Optional[str] = None, temperature: float = 0.3):
        # Slightly higher temperature for creative generation
        # Use unified client with OpenAI-first, Groq fallback
        self.llm = get_chat_llm(model=model, temperature=temperature)
    
    def generate_form(
        self,
        rfp_title: str,
        rfp_scope: str,
        rfp_requirements: List[str],
        project_type: Optional[str] = None
    ) -> ProposalFormStructure:
        """
        Generate a proposal form based on RFP information.
        
        Args:
            rfp_title: Title of the RFP
            rfp_scope: Project scope/description
            rfp_requirements: List of requirements
            project_type: Optional project type for better categorization
        """
        print(f"--- AI Form Generator: Creating form for '{rfp_title}' ---")
        
        # Step 1: Generate line items
        generated = self._generate_line_items(rfp_title, rfp_scope, rfp_requirements, project_type)
        
        # Step 2: Convert to ProposalFormStructure
        structure = self._convert_to_structure(generated, rfp_title)
        
        print(f"  ✓ Generated {len(structure.rows)} line items in {len(structure.sections)} sections")
        
        return structure
    
    def _generate_line_items(
        self,
        rfp_title: str,
        rfp_scope: str,
        rfp_requirements: List[str],
        project_type: Optional[str]
    ) -> GeneratedProposalForm:
        """Generate line items using AI."""
        
        structured_llm = self.llm.with_structured_output(GeneratedProposalForm)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", """You are an expert Quantity Surveyor creating a proposal submission form.

Based on the RFP information provided, create a PROFESSIONAL bid form that vendors can fill out.

GUIDELINES:
1. Create logical SECTIONS based on the work scope:
   - Group related items (e.g., "Site Work", "Electrical", "Plumbing")
   - Use Roman numerals for major sections (I, II, III...)
   - Use numbers for items within sections (1, 2, 3...)

2. For each LINE ITEM:
   - Clear, specific description of work
   - Appropriate unit of measure:
     * LS (Lump Sum) - for complete tasks
     * SF (Square Feet) - for area-based work
     * LF (Linear Feet) - for linear work
     * HR (Hours) - for time-based work
     * EA (Each) - for countable items
   - Quantity as "TBD" unless specified in requirements

3. Always include:
   - General Conditions section (overhead, mobilization, permits)
   - Allowance for additions/alternates

4. Make it PROFESSIONAL and COMPREHENSIVE but not excessive."""),
            ("user", """RFP Information:

Title: {rfp_title}
Project Type: {project_type}

Scope:
{rfp_scope}

Requirements:
{requirements}

Generate a professional proposal submission form.""")
        ])
        
        chain = prompt | structured_llm
        
        return chain.invoke({
            "rfp_title": rfp_title,
            "project_type": project_type or "General",
            "rfp_scope": rfp_scope,
            "requirements": "\n".join([f"- {req}" for req in rfp_requirements])
        })
    
    def _convert_to_structure(
        self,
        generated: GeneratedProposalForm,
        rfp_title: str
    ) -> ProposalFormStructure:
        """Convert generated form to ProposalFormStructure."""
        
        # Convert line items to DiscoveredFormRow
        rows = []
        for item in generated.line_items:
            rows.append(DiscoveredFormRow(
                section=item.section,
                item_id=item.item_id,
                description=item.description,
                values={
                    "quantity": item.quantity or "TBD",
                    "unit": item.unit
                }
            ))
        
        # Add General Conditions if requested
        if generated.include_general_conditions:
            gc_items = [
                ("General Conditions", "LS"),
                ("Mobilization and Demobilization", "LS"),
                ("Permits and Fees", "LS"),
                ("Insurance and Bonds", "LS"),
            ]
            for i, (desc, unit) in enumerate(gc_items, 1):
                rows.append(DiscoveredFormRow(
                    section="General Conditions",
                    item_id=str(i),
                    description=desc,
                    values={"quantity": "1", "unit": unit}
                ))
        
        # Add Additions table placeholders if requested
        if generated.include_additions:
            for i in range(1, 5):
                rows.append(DiscoveredFormRow(
                    section="Additions",
                    item_id=f"Ad{i}",
                    description="",
                    values={"quantity": "", "unit": ""}
                ))
        
        # Create table structures
        tables = [
            DiscoveredTable(
                table_title=generated.form_title,
                table_type="pricing_section",
                columns=[
                    DiscoveredColumn(name="Item", column_type="identifier", is_fixed=True, sample_values=["1", "2"]),
                    DiscoveredColumn(name="Description of Work", column_type="description", is_fixed=True, sample_values=[]),
                    DiscoveredColumn(name="Quantity", column_type="quantity", is_fixed=False, sample_values=["TBD"]),
                    DiscoveredColumn(name="Unit", column_type="unit", is_fixed=False, sample_values=["SF", "LF"]),
                    DiscoveredColumn(name="Unit Cost", column_type="price", is_fixed=False, sample_values=[]),
                    DiscoveredColumn(name="Total", column_type="total", is_fixed=False, sample_values=[]),
                ],
                section_headers=generated.sections
            )
        ]
        
        if generated.include_general_conditions:
            tables.append(DiscoveredTable(
                table_title="General Conditions",
                table_type="general_conditions",
                columns=[
                    DiscoveredColumn(name="Description of Work", column_type="description", is_fixed=True, sample_values=[]),
                    DiscoveredColumn(name="Quantity", column_type="quantity", is_fixed=False, sample_values=["1"]),
                    DiscoveredColumn(name="Unit", column_type="unit", is_fixed=False, sample_values=["LS"]),
                    DiscoveredColumn(name="Unit Cost", column_type="price", is_fixed=False, sample_values=[]),
                    DiscoveredColumn(name="Total", column_type="total", is_fixed=False, sample_values=[]),
                    DiscoveredColumn(name="%", column_type="percentage", is_fixed=False, sample_values=[]),
                ],
                section_headers=[]
            ))
        
        return ProposalFormStructure(
            form_title=f"{rfp_title} - PROPOSAL SUBMISSION FORM",
            tables=tables,
            fixed_columns=["Item", "Description of Work"],
            vendor_columns=["Quantity", "Unit", "Unit Cost", "Total"],
            sections=generated.sections + (["General Conditions", "Additions"] if generated.include_general_conditions else []),
            rows=rows
        )


# --- Test ---
if __name__ == "__main__":
    print("=== Testing AI Form Generator ===\n")
    
    generator = AIFormGenerator()
    
    # Test with sample RFP data (like from AI consultant chat)
    form = generator.generate_form(
        rfp_title="Office Building HVAC Maintenance",
        rfp_scope="""
        Annual preventive maintenance and repair services for HVAC systems 
        in a 10-story office building. Includes quarterly inspections, 
        filter replacements, and emergency repair services.
        """,
        rfp_requirements=[
            "Quarterly preventive maintenance visits",
            "24/7 emergency response within 4 hours",
            "Filter replacement every 3 months",
            "Annual duct cleaning",
            "Monthly system monitoring and reporting",
            "Parts and labor for repairs"
        ],
        project_type="HVAC Maintenance"
    )
    
    print(f"\n--- Generated Form ---")
    print(f"Title: {form.form_title}")
    print(f"Sections: {form.sections}")
    print(f"Fixed Columns: {form.fixed_columns}")
    print(f"Vendor Columns: {form.vendor_columns}")
    print(f"\nLine Items ({len(form.rows)}):")
    for row in form.rows:
        print(f"  [{row.item_id}] {row.section}: {row.description[:50]}... | {row.values}")
